/*
@title: Tic Tac Toe
@author: taco
@tags: [tacostictactoe.js]
@addedOn: 2024-7-3
*/

let player = "X"; // the player
let gameOver = false; // game over flag

// bitmaps
const x = "x";
const o = "o";
const e = "e";
const a = "a"; // x axis
const b = "b"; // y axis
setLegend(
  [x, bitmap`
................
................
................
....00....00....
.....00..00.....
......0000......
.......00.......
.......00.......
......0000......
.....00..00.....
....00....00....
................
................
................
................
................`],
  [o, bitmap`
................
................
................
......0000......
....00....00....
...00......00...
...00......00...
...00......00...
...00......00...
....00....00....
......0000......
................
................
................
................
................`],
  [e, bitmap`
................
................
................
................
.....0000.......
....0....0......
.........0......
.........0......
........0.......
.......0........
......0.........
................
................
......0.........
................
................`],
  [a, bitmap`
................
................
................
................
.......6........
......666.......
.....66666......
....6666666.....
......666.......
......666.......
......666.......
......666.......
......666.......
......666.......
................
................`],
  [b, bitmap`
................
................
................
................
.........6......
.........66.....
...666666666....
...6666666666...
...666666666....
.........66.....
.........6......
................
................
................
................
................`]
  )

// the board
const board = map`
beee
.eee
.eee
.a..`;
setMap(board);
/*
// check and display the intersection coordinates
function checkIntersection() {
  const aSprite = getFirst(a);
  const bSprite = getFirst(b);

  const xCoord = bSprite.x;
  const yCoord = aSprite.y;

  clearText();
  addText(`X: ${xCoord}, Y: ${yCoord}`, { x: 1, y: 10, color: color`3` });
}
*/

// Move `a` left and right with 'a' and 'd'
onInput("a", () => {
  const aSprite = getFirst(a);
  if (aSprite.x > 0) {
    aSprite.x -= 1;
  }
});

onInput("d", () => {
  const aSprite = getFirst(a);
  if (aSprite.x < 3) {
    aSprite.x += 1;
  }
});

// Move `b` up and down with 'w' and 's'
onInput("w", () => {
  const bSprite = getFirst(b);
  if (bSprite.y > 0) {
    bSprite.y -= 1;
  }
});

onInput("s", () => {
  const bSprite = getFirst(b);
  if (bSprite.y < 3) {
    bSprite.y += 1;
  }
});



/*
// new game function
function newGame() {
 const board = map`
...
...
...`; // reset board
  player = "X"; // Start with player X
  gameOver = false; // reset gO flag
  setMap(board);
  clearText();
  addText("X's turn", { x: 1, y: 12, color: color`3` });
}

*/